/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chickenleg_remote_MemoryEconomiseScreenTaker */

#ifndef _Included_com_chickenleg_remote_MemoryEconomiseScreenTaker
#define _Included_com_chickenleg_remote_MemoryEconomiseScreenTaker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chickenleg_remote_MemoryEconomiseScreenTaker
 * Method:    take
 * Signature: (IIII[I)V
 */
JNIEXPORT void JNICALL Java_com_chickenleg_remote_MemoryEconomiseScreenTaker_take(JNIEnv *, jobject, jint, jint, jint, jint, jintArray);

JNIEXPORT jint* JNICALL checkParameters(JNIEnv *env, jobject _this, jint imgx, jint imgy, jint w, jint h, jintArray dest);

#ifdef __cplusplus
}
#endif
#endif
